# Generated by Django 4.0.4 on 2022-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tiempoPreparacion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('alimento', models.ManyToManyField(to='res.alimento')),
            ],
        ),
    ]
